Add yaml file for a new plugin for mixing-security-realm
jenkins-infra/repository-permissions-updater pull request #1681
Opened 2020-09-30 08:50 UTC by wenjunxiao

# Description

Plugin hosting request: https://issues.jenkins-ci.org/browse/HOSTING-997
Repository link: https://github.com/jenkinsci/mixing-security-realm-plugin

# Submitter checklist for adding or changing permissions

### Always

- [x] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [x] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [x] Make sure the file is created in `permissions/` directory
- [x] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [x] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [x] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [x] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [x] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [x] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [x] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@daniel-beck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

2020-10-02 05:19 UTC, yJunS requested changes

2020-10-02 05:19 UTC, yJunS commented on permissions/plugin-mixing-security-realm.yml
> +- "org/jenkins-ci/plugins/mixing-security-realm"
Please check the paths

2020-10-02 16:00 UTC, slide commented on permissions/plugin-mixing-security-realm.yml
> +- "org/jenkins-ci/plugins/mixing-security-realm"
```suggestion
- "io/jenkins/plugins/mixing-security-realm"
```

See https://github.com/jenkinsci/mixing-security-realm-plugin/blob/master/pom.xml#L10 and https://github.com/jenkinsci/mixing-security-realm-plugin/blob/master/pom.xml#L11

2020-10-02 16:14 UTC, slide commented
```User name not known to Artifactory: promissing```

2020-10-06 09:40 UTC, wenjunxiao commented
> `User name not known to Artifactory: promissing`

@slide This is my user name on https://issues.jenkins-ci.org/secure/ViewProfile.jspa?name=promissing,  isn't it the username of this website?

2020-10-06 13:33 UTC, MarkEWaite commented
> > `User name not known to Artifactory: promissing`
> 
> @slide This is my user name on https://issues.jenkins-ci.org/secure/ViewProfile.jspa?name=promissing, isn't it the username of this website?

@wenjunxiao I believe that you need to login at least once to https://repo.jenkins-ci.org/ as that user in order for Artifactory to know that you are a user of that system.  We have over 100 000 users in the Jenkins accounts database and we only want to create accounts in repo.jenkins-ci.org when a user will need that account.

2020-10-06 14:33 UTC, wenjunxiao commented
> > > `User name not known to Artifactory: promissing`
> > 
> > 
> > @slide This is my user name on https://issues.jenkins-ci.org/secure/ViewProfile.jspa?name=promissing, isn't it the username of this website?
> 
> @wenjunxiao I believe that you need to login at least once to https://repo.jenkins-ci.org/ as that user in order for Artifactory to know that you are a user of that system. We have over 100 000 users in the Jenkins accounts database and we only want to create accounts in repo.jenkins-ci.org when a user will need that account.

Thanks!

2020-10-07 16:22 UTC, merged