add cloudbees-developers to second tier
jenkins-infra/repository-permissions-updater pull request #2266
Opened 2021-12-17 17:51 UTC by car-roll

# Description
This PR adds the team `cloudbees-developers` to another possible set of cloudbees-owned plugins.
Keeping in draft right now as this is a first pass.

# Submitter checklist for adding or changing permissions

### Always

- [ ] Add link to plugin/component Git repository in description above

### For a newly hosted plugin only

- [ ] Add link to resolved HOSTING issue in description above

### For a new permissions file only

- [ ] Make sure the file is created in `permissions/` directory
- [ ] `artifactId` (pom.xml) is used for `name` (permissions YAML file).
- [ ] [`groupId` / `artifactId` (pom.xml) are correctly represented in `path` (permissions YAML file)](https://github.com/jenkins-infra/repository-permissions-updater/#managing-permissions)
- [ ] Check that the file is named `plugin-${artifactId}.yml` for plugins

### When adding new uploaders (this includes newly created permissions files)

- [ ] [Make sure to `@`mention an existing maintainer to confirm the permissions request, if applicable](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)
- [ ] Use the Jenkins community (LDAP) account name in the YAML file, not the GitHub account name
- [ ] Make sure to `@`mention the users being added so their GitHub account names are known if they require GitHub merge access (see below).
- [ ] [All newly added users have logged in to Artifactory at least once](https://github.com/jenkins-infra/repository-permissions-updater/#requesting-permissions)

### Reviewer checklist (not for requesters!)

- [ ] Check this if newly added person also needs to be given merge permission to the GitHub repo (please @ the people/person with their GitHub username in this issue as well). If needed, it can be done using an [IRC Bot command](https://jenkins.io/projects/infrastructure/ircbot/#github-repo-management)
- [ ] Check that the `$pluginId Developers` team has `Admin` permissions while granting the access.
- [ ] In the case of plugin adoption, ensure that the Jenkins Jira default assignee is either removed or changed to the new maintainer.
- [ ] If security contacts are changed (this includes add/remove), ping the security officer (currently `@Wadeck`) in this pull request. If an email contact is changed, wait for approval from the security officer.

There are [IRC Bot commands](https://jenkins.io/projects/infrastructure/ircbot/#issue-tracker-management) for it

2021-12-22 14:09 UTC, jglick commented
compare #2265

2021-12-22 14:17 UTC, jglick commented on permissions/component-pipeline-model-json-shaded.yml
> +- "@cloudbees-developers"
Does this still exist?

2021-12-22 14:17 UTC, jglick commented on permissions/plugin-blueocean-autofavorite.yml
> +- "@cloudbees-developers"
I hope only to deprecate it!

2021-12-22 14:17 UTC, jglick commented on permissions/plugin-blueocean-executor-info.yml
> +- "@cloudbees-developers"
IIRC this was already deleted?

2021-12-22 14:17 UTC, jglick commented on permissions/plugin-pipeline-model-declarative-agent.yml
> +- "@cloudbees-developers"
Was deleted years ago.

2021-12-24 18:49 UTC, oleg-nenashev requested changes
Same as #2265

2021-12-29 15:53 UTC, jtnord commented on permissions/plugin-caffeine-api.yml
> +- "@cloudbees-developers"
+1

2023-02-23 16:47 UTC, car-roll commented
obsolete PR, closing

2023-02-23 16:47 UTC, closed without merging