Suspend Gradle checks for new plugins
jenkins-infra/repository-permissions-updater pull request #3015
Opened 2022-12-06 23:41 UTC by NotMyFault

Picks up my comment from https://github.com/jenkins-infra/helpdesk/issues/3279#issuecomment-1339681950

I suggest we do no longer host new plugins using the JPI plugin, until it supports the same scope as the maven architecture. As of now, there's no built-in release functionality, no support for JEP-229 (CD) and probably a few other components, which have been added within the past years.

2022-12-07 08:54 UTC, timja requested changes
this should be a discussion on the dev mailing list first

2022-12-07 21:36 UTC, NotMyFault commented
Linking https://groups.google.com/g/jenkinsci-dev/c/lHQAiEepBiw for cross reference

2022-12-21 22:33 UTC, NotMyFault commented
Overall consensus is positive, do you think we can continue with this PR?

2022-12-22 08:05 UTC, timja approved these changes

2022-12-22 08:05 UTC, merged